name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  daemon:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Install dependencies with apt
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler libprotobuf-dev

    - name: Build
      run: |
        cd ./daemon
        cargo build --verbose
        
    - name: Test
      run: |
        cd ./daemon
        cargo test --verbose
        
    - name: Format
      run: |
        cd ./daemon
        cargo fmt --check

  server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: |
        cd ./server
        cargo build --verbose
        
    - name: Test
      run: |
        cd ./server
        cargo test --verbose
        
    - name: Format
      run: |
        cd ./server
        cargo fmt --check

  client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: |
        cd ./client
        cargo build --verbose
        
    - name: Test
      run: |
        cd ./client
        cargo test --verbose
        
    - name: Format
      run: |
        cd ./client
        cargo fmt --check

  common:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: |
        cd ./common
        cargo build --verbose
        
    - name: Test
      run: |
        cd ./common
        cargo test --verbose
        
    - name: Format
      run: |
        cd ./common
        cargo fmt --check
