name: Build and test server

on:
  push:
    branches: [ "main" ]
    paths:
      - "server/"
      - "common/"
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/"
      - "common"

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

defaults:
  run:
    working_directory: server

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: |
        cargo build --verbose
        
    - name: Test
      run: |
        cargo test --verbose
        
    - name: Format
      run: |
        cargo fmt --check